name: CI Workflow

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '37 4 * * *'

env:
  IMAGE_NAME: cert-manager-webhook-hetzner
  IMAGE_VERSION: 1.0.0
  HELM_CHART_VERSION: 0.1.0
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Build Webhook
        run: CGO_ENABLED=0 go build -v -buildmode=pie -buildvcs=false -ldflags="-s -w" ./cmd/webhook

      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }} ${{ env.IMAGE_VERSION }}-${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          oci: true

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        env:
          IMAGE_REGISTRY_IMAGE: ${{ env.IMAGE_REGISTRY }}/${{ steps.build-image.outputs.image }}
          HELM_CHART_PATH: ./deployments/helm
        run: |
          # Replace image.repository in Helm Chart by actual repository
          yq -i '.image.repository = strenv(IMAGE_REGISTRY_IMAGE)' "${HELM_CHART_PATH}/values.yaml"

          # Print Helm Chart templates
          helm template --debug "${{ steps.build-image.outputs.image }}" "${HELM_CHART_PATH}"

          # Lint Helm Chart
          helm lint --strict "${HELM_CHART_PATH}"

          # Package Helm Chart
          helm package "${HELM_CHART_PATH}" --app-version "${IMAGE_VERSION}" --version "${HELM_CHART_VERSION}"

      - name: Push Container Image To GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image }}
          IMAGE_TAGS: ${{ steps.build-image.outputs.tags }}
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
        run: |
          if [ -z "${IMAGE_NAME}" ]; then
            echo "Image name has not been provided" >&2
            exit 1
          fi
          if [ -z "${IMAGE_TAGS}" ]; then
            echo "No image tags have been provided" >&2
            exit 2
          fi
          if [ -z "${IMAGE_REGISTRY}" ]; then
            echo "Image registry has not been provided" >&2
            exit 1
          fi

          # Construct registry URL and image tags.
          # The registry name as well as the image name are normalized to lowercase.
          REGISTRY_IMAGE_URL="${IMAGE_REGISTRY,,}/${IMAGE_NAME,,}"
          readarray -d ' ' -t IMAGE_TAG_LIST < <(printf '%s' "${IMAGE_TAGS}")

          # Log in to the registry
          echo "Logging in to registry ${IMAGE_REGISTRY,,} with user ${{ github.actor }}"
          podman login --password-stdin --username "${{ github.actor }}" "${IMAGE_REGISTRY,,}" < <(printf '%s' "${{ secrets.GITHUB_TOKEN }}")

          # Push image for each provided tag
          for IMAGE_TAG in "${IMAGE_TAG_LIST[@]}"; do
            echo "Pushing image ${IMAGE_NAME} to ${REGISTRY_IMAGE_URL} with tag ${IMAGE_TAG}"

            podman push --disable-content-trust "${IMAGE_NAME}" "${REGISTRY_IMAGE_URL}:${IMAGE_TAG}"
          done

          # Log out of the registry
          echo "Logging out of registry ${IMAGE_REGISTRY,,}"
          podman logout "${IMAGE_REGISTRY,,}"

      - name: Publish Helm Chart
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          # Log in to GitHub Container Registry
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u "${{ github.actor }}" --password-stdin "${IMAGE_REGISTRY}"

          # Push Helm Chart
          helm push "${{ steps.build-image.outputs.image }}-${HELM_CHART_VERSION}.tgz" "oci://${{ env.IMAGE_REGISTRY }}/${{ steps.build-image.outputs.image }}"

          # Log out of GitHub Container Registry
          helm registry logout "${IMAGE_REGISTRY}"
